/**
 * Seed script — creates:
 *   1. Admin user  (admin@powerplan.app / Admin123!)
 *   2. Demo client (demo@example.com / Demo123!)
 *   3. One completed "BookSmart" demo project with all 12 planning phases
 *
 * Run: node backend/seed/seed.js
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const bcrypt   = require('bcryptjs');

// Load models
require('../src/models/index');
const User     = require('../src/models/User');
const Project  = require('../src/models/Project');
const Phase    = require('../src/models/Phase');
const Document = require('../src/models/Document');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/power-plan';

const PHASES = [
  { type: 'idea_understanding',  agentName: 'IdeaAnalystAgent',      label: 'Idea Understanding' },
  { type: 'product_discovery',   agentName: 'ProductDiscoveryAgent',  label: 'Product Discovery' },
  { type: 'market_analysis',     agentName: 'MarketAnalystAgent',     label: 'Market Analysis' },
  { type: 'ux_architecture',     agentName: 'UXArchitectAgent',       label: 'UX Architecture' },
  { type: 'tech_architecture',   agentName: 'TechArchitectAgent',     label: 'Technical Architecture' },
  { type: 'system_design',       agentName: 'SystemDesignAgent',      label: 'System Design' },
  { type: 'database_design',     agentName: 'DatabaseAgent',          label: 'Database Design' },
  { type: 'ai_agent_system',     agentName: 'AIAgentSystemAgent',     label: 'AI Agent System' },
  { type: 'orchestration',       agentName: 'OrchestrationAgent',     label: 'Orchestration' },
  { type: 'dev_planning',        agentName: 'DevPlannerAgent',        label: 'Dev Planning' },
  { type: 'qa_strategy',         agentName: 'QAAgent',                label: 'QA Strategy' },
  { type: 'devops_strategy',     agentName: 'DevOpsAgent',            label: 'DevOps Strategy' },
];

const DEMO_DOC = (label) => `# ${label}

## Summary

This is a **demo document** generated by the Power Plan seed script.

Power Plan's AI pipeline analyzes your idea across 12 phases — each one producing a detailed,
enterprise-grade planning document like this one.

---

## What the AI does in this phase

In the **${label}** phase, Claude analyzes all previous documents and generates a comprehensive
deliverable. The output is instantly viewable, reviewable, and refineable (up to 2 times per phase).

---

## Next step

Click **Approve & Continue** to advance the pipeline to the next phase.
`;

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB:', MONGO_URI);

  // ── 1. Admin user ─────────────────────────────────────────────────────────
  let admin = await User.findOne({ email: 'admin@powerplan.app' });
  if (!admin) {
    admin = await User.create({
      name:         'Platform Admin',
      email:        'admin@powerplan.app',
      passwordHash: await bcrypt.hash('Admin123!', 10),
      role:         'admin',
      plan:         'pro',
      isActive:     true,
    });
    console.log('Created admin user:', admin.email);
  } else {
    console.log('Admin user already exists, skipping.');
  }

  // ── 2. Demo client ────────────────────────────────────────────────────────
  let demo = await User.findOne({ email: 'demo@example.com' });
  if (!demo) {
    demo = await User.create({
      name:         'Demo User',
      email:        'demo@example.com',
      passwordHash: await bcrypt.hash('Demo123!', 10),
      role:         'client',
      plan:         'pro',
      isActive:     true,
    });
    console.log('Created demo user:', demo.email);
  } else {
    console.log('Demo user already exists, skipping.');
  }

  // ── 3. Demo project ───────────────────────────────────────────────────────
  const existingProject = await Project.findOne({ ownerId: demo._id, title: 'BookSmart' });
  if (existingProject) {
    console.log('Demo project already exists, skipping.');
    await mongoose.disconnect();
    return;
  }

  const project = await Project.create({
    title:           'BookSmart',
    idea:            'אפליקציה שעוזרת לאנשים לעקוב אחרי הספרים שקראו, לקבל המלצות מותאמות אישית ולשתף ביקורות עם חברים.',
    ownerId:         demo._id,
    status:          'live',
    completionPercent: 100,
    currentPhaseIndex: 12,
    approvalGates:   true,
    deployedUrl:     'https://booksmart-demo.onrender.com',
    stack:           'dor-cellular',
    discoveryAnswers: [
      { question: 'מה הבעיה המרכזית שהאפליקציה פותרת?', answer: 'אנשים קוראים ספרים אבל שוכחים מה קראו ולא מוצאים המלצות אמינות' },
      { question: 'מי המשתמש?', answer: 'קוראים נלהבים בגילאי 25-45, בעיקר נשים עובדות' },
      { question: 'מה המודל העסקי?', answer: 'Freemium — בסיסי חינמי, Pro ב-₪29/חודש' },
      { question: 'כמה משתמשים ב-12 חודשים?', answer: 'יעד: 10,000 משתמשים רשומים' },
      { question: 'האם יש צורך ב-Realtime?', answer: 'כן, צ\'אט עם חברים על ספרים' },
      { question: 'Stack?', answer: 'סטנדרטי — React + Node + MongoDB' },
      { question: 'זמן לפיתוח MVP?', answer: '3 חודשים' },
    ],
    infra: {
      githubRepoUrl: 'https://github.com/power-plan-apps/booksmart',
      renderUrl:     'https://booksmart-demo.onrender.com',
    },
  });

  console.log('Created demo project:', project.title);

  // ── 4. Create phases + documents ─────────────────────────────────────────
  for (let i = 0; i < PHASES.length; i++) {
    const cfg = PHASES[i];
    const phase = await Phase.create({
      projectId:   project._id,
      type:        cfg.type,
      index:       i,
      agentName:   cfg.agentName,
      status:      'completed',
      startedAt:   new Date(Date.now() - (PHASES.length - i) * 3 * 60 * 1000),
      completedAt: new Date(Date.now() - (PHASES.length - i - 1) * 3 * 60 * 1000),
      tokensUsed:  Math.floor(1000 + Math.random() * 2000),
      refineCount: 0,
    });

    const content = DEMO_DOC(cfg.label);
    await Document.create({
      projectId:  project._id,
      phaseId:    phase._id,
      type:       cfg.type,
      content,
      summary:    content.slice(0, 500),
      version:    1,
      isApproved: true,
    });

    console.log(`  Phase ${i}: ${cfg.label} ✓`);
  }

  console.log('\n✅ Seed complete!');
  console.log('   Admin:  admin@powerplan.app / Admin123!');
  console.log('   Demo:   demo@example.com    / Demo123!');
  console.log('   Project: BookSmart (live)');

  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
