const { Octokit } = require('@octokit/rest');
const env         = require('../config/env');

function _octokit() {
  if (!env.GITHUB_TOKEN) throw new Error('GITHUB_TOKEN not configured');
  return new Octokit({ auth: env.GITHUB_TOKEN });
}

function _repoName(projectId, title) {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9֐-׿\s]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 30)
    .replace(/-+$/, '');
  return `${slug || 'app'}-${projectId.toString().slice(-6)}`;
}

async function createRepo(projectId, title) {
  const octokit  = _octokit();
  const repoName = _repoName(projectId, title);

  const { data } = await octokit.repos.createInOrg({
    org:         env.GITHUB_ORG,
    name:        repoName,
    private:     true,
    description: `Generated by Power Plan ⚡ — ${title}`,
    auto_init:   false,
  });

  return { repoName, repoUrl: data.html_url, cloneUrl: data.clone_url, fullName: data.full_name };
}

// Push files using GitHub Git Trees API (no git binary required)
// files: [{ path: 'backend/src/index.js', content: '...' }]
async function pushFiles(fullName, files) {
  const octokit = _octokit();
  const [owner, repo] = fullName.split('/');

  // Create blobs (batch serially to avoid rate limits)
  const blobShas = [];
  for (const file of files) {
    const { data } = await octokit.git.createBlob({
      owner, repo,
      content:  Buffer.from(file.content, 'utf8').toString('base64'),
      encoding: 'base64',
    });
    blobShas.push(data.sha);
  }

  // Build tree
  const tree = files.map((f, i) => ({
    path: f.path,
    mode: '100644',
    type: 'blob',
    sha:  blobShas[i],
  }));

  const { data: treeData } = await octokit.git.createTree({ owner, repo, tree });

  // Create commit (orphan — no parent)
  const { data: commitData } = await octokit.git.createCommit({
    owner, repo,
    message: '⚡ Initial commit — generated by Power Plan',
    tree:    treeData.sha,
    parents: [],
  });

  // Create main branch ref
  await octokit.git.createRef({
    owner, repo,
    ref: 'refs/heads/main',
    sha: commitData.sha,
  });

  return commitData.sha;
}

async function deleteRepo(fullName) {
  if (!fullName) return;
  try {
    const octokit = _octokit();
    const [owner, repo] = fullName.split('/');
    await octokit.repos.delete({ owner, repo });
  } catch (_) {
    // non-fatal
  }
}

module.exports = { createRepo, pushFiles, deleteRepo };
