export const PHASE_GROUPS = {
  PLANNING: 'planning',
  BUILDING: 'building',
  DEPLOYING: 'deploying',
};

export const PLANNING_PHASES = [
  {
    index: 0,
    type: 'idea_understanding',
    name: 'Idea Understanding',
    nameHe: 'הבנת הרעיון',
    icon: '💡',
    agentName: 'IdeaAnalystAgent',
    narrativeTemplate: 'אני CTO שמנתח את הרעיון שלך ומזהה סיכונים טכניים...',
    meetingParticipants: ['pm', 'cto'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 1,
    type: 'product_discovery',
    name: 'Product Discovery',
    nameHe: 'גילוי מוצרי',
    icon: '📋',
    agentName: 'ProductDiscoveryAgent',
    narrativeTemplate: 'אני Product Manager שבונה PRD מלא...',
    meetingParticipants: ['pm', 'cto', 'ux'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 2,
    type: 'market_analysis',
    name: 'Market Analysis',
    nameHe: 'ניתוח שוק',
    icon: '📊',
    agentName: 'MarketAnalystAgent',
    narrativeTemplate: 'אני בוחן את השוק ומחפש מתחרים קיימים...',
    meetingParticipants: ['pm', 'cto'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 3,
    type: 'ux_architecture',
    name: 'UX Architecture',
    nameHe: 'ארכיטקטורת UX',
    icon: '🎨',
    agentName: 'UXArchitectAgent',
    narrativeTemplate: 'אני UX Designer שחושב על flows וממשקים...',
    meetingParticipants: ['ux', 'pm', 'frontend'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 4,
    type: 'tech_architecture',
    name: 'Technical Architecture',
    nameHe: 'ארכיטקטורה טכנית',
    icon: '🏗️',
    agentName: 'TechArchitectAgent',
    narrativeTemplate: 'אני Architect שמחליט על הסטק הטכנולוגי...',
    meetingParticipants: ['cto', 'backend', 'frontend'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 5,
    type: 'system_design',
    name: 'System Design',
    nameHe: 'עיצוב מערכת',
    icon: '⚙️',
    agentName: 'SystemDesignAgent',
    narrativeTemplate: 'אני מתכנן את ה-API contracts וזרימת הנתונים...',
    meetingParticipants: ['cto', 'backend', 'devops'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 6,
    type: 'database_design',
    name: 'Database Design',
    nameHe: 'עיצוב בסיס נתונים',
    icon: '🗄️',
    agentName: 'DatabaseAgent',
    narrativeTemplate: 'אני מגדיר schemas, indexes ומבנה הנתונים...',
    meetingParticipants: ['cto', 'backend'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 7,
    type: 'ai_agent_system',
    name: 'AI Agent System',
    nameHe: 'מערכת סוכני AI',
    icon: '🤖',
    agentName: 'AIAgentSystemAgent',
    narrativeTemplate: 'אני מגדיר את מערכת ה-AI agents של האפליקציה...',
    meetingParticipants: ['cto', 'pm'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 8,
    type: 'orchestration',
    name: 'Orchestration',
    nameHe: 'תהליכי רקע',
    icon: '🎼',
    agentName: 'OrchestrationAgent',
    narrativeTemplate: 'אני מתכנן את ארכיטקטורת התזמור ומניעת קונפליקטים...',
    meetingParticipants: ['cto', 'devops'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 9,
    type: 'dev_planning',
    name: 'Dev Planning',
    nameHe: 'תכנון פיתוח',
    icon: '📅',
    agentName: 'DevPlannerAgent',
    narrativeTemplate: 'אני Engineering Manager שמפרק למשימות ספרינטים...',
    meetingParticipants: ['pm', 'backend', 'frontend', 'qa'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 10,
    type: 'qa_strategy',
    name: 'QA Strategy',
    nameHe: 'אסטרטגיית QA',
    icon: '✅',
    agentName: 'QAAgent',
    narrativeTemplate: 'אני QA Engineer שמגדיר את אסטרטגיית הבדיקות...',
    meetingParticipants: ['qa', 'pm', 'cto'],
    group: PHASE_GROUPS.PLANNING,
  },
  {
    index: 11,
    type: 'devops_strategy',
    name: 'DevOps Strategy',
    nameHe: 'אסטרטגיית DevOps',
    icon: '🚀',
    agentName: 'DevOpsAgent',
    narrativeTemplate: 'אני מגדיר CI/CD pipeline, Git Flow ומוניטורינג...',
    meetingParticipants: ['devops', 'cto', 'security'],
    group: PHASE_GROUPS.PLANNING,
  },
];

export const CODEGEN_PHASES = [
  {
    index: 12,
    type: 'db_schema',
    name: 'Database Schema',
    nameHe: 'סכמת בסיס נתונים',
    icon: '🗄️',
    agentName: 'DatabaseSchemaAgent',
    narrativeTemplate: 'אני יוצר את models וה-seed script...',
    group: PHASE_GROUPS.BUILDING,
  },
  {
    index: 13,
    type: 'backend_scaffold',
    name: 'Backend Scaffold',
    nameHe: 'קוד Backend',
    icon: '⚙️',
    agentName: 'BackendScaffoldAgent',
    narrativeTemplate: 'אני כותב controllers, services, routes ו-middleware...',
    group: PHASE_GROUPS.BUILDING,
  },
  {
    index: 14,
    type: 'frontend_scaffold',
    name: 'Frontend Scaffold',
    nameHe: 'קוד Frontend',
    icon: '🎨',
    agentName: 'FrontendScaffoldAgent',
    narrativeTemplate: 'אני בונה pages, components, store slices ו-API layer...',
    group: PHASE_GROUPS.BUILDING,
  },
  {
    index: 15,
    type: 'tests',
    name: 'Tests',
    nameHe: 'בדיקות',
    icon: '🧪',
    agentName: 'TestsAgent',
    narrativeTemplate: 'אני כותב Jest + Supertest tests...',
    group: PHASE_GROUPS.BUILDING,
  },
  {
    index: 16,
    type: 'config',
    name: 'Config & Setup',
    nameHe: 'הגדרות',
    icon: '📦',
    agentName: 'ConfigAgent',
    narrativeTemplate: 'אני מגדיר package.json, .env.example, Docker...',
    group: PHASE_GROUPS.BUILDING,
  },
  {
    index: 17,
    type: 'review',
    name: 'Code Review',
    nameHe: 'בדיקת קוד',
    icon: '🔍',
    agentName: 'ReviewAgent',
    narrativeTemplate: 'אני בודק consistency, naming ו-API contracts...',
    group: PHASE_GROUPS.BUILDING,
  },
];

export const ALL_PHASES = [...PLANNING_PHASES, ...CODEGEN_PHASES];

// Maps planning phase index → which team member leads that phase (for team status strip)
export const PHASE_LEAD = {
  0: 'pm', 1: 'pm', 2: 'pm',
  3: 'ux',
  4: 'cto', 5: 'cto', 7: 'cto', 8: 'cto',
  6: 'backend',
  9: 'pm',
  10: 'qa',
  11: 'devops',
};

export const TEAM_MEMBERS = {
  cto:      { name: 'Sarah', role: 'CTO',           color: '#7c3aed', emoji: '🏗️' },
  pm:       { name: 'David', role: 'Product Manager', color: '#2563eb', emoji: '👨‍💼' },
  ux:       { name: 'Alex',  role: 'UX Designer',    color: '#ca8a04', emoji: '🎨' },
  backend:  { name: 'Maya',  role: 'Backend Dev',    color: '#16a34a', emoji: '⚙️' },
  frontend: { name: 'Tom',   role: 'Frontend Dev',   color: '#dc2626', emoji: '🖥️' },
  qa:       { name: 'Dana',  role: 'QA Engineer',    color: '#ea580c', emoji: '✅' },
  devops:   { name: 'Eli',   role: 'DevOps',         color: '#4b5563', emoji: '🚀' },
  security: { name: 'Noa',   role: 'Security',       color: '#db2777', emoji: '🔒' },
};
